### ISSUE TITLE
does not build against libalpm.so.9 (pacman-4.2)

### ISSUE THREAD

**Issue by majewsky** [juster/perl-alpm#3]
I haven't previously tried building perl-alpm against older libalpm's (dates and docs suggest that the last release was built against libalpm.so.8 as shipped with pacman-4.1). Building against pacman-4.2, I get the following error in the tests:

```
$ prove -b t/03-Package.t 
t/03-Package.t .. 1/? 
#   Failed test 'load the simpletest/foo package file'
#   at t/03-Package.t line 24.
Can't locate object method "strerror" via package "ALPM" at t/03-Package.t line 25.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/03-Package.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

Test Summary Report
-------------------
t/03-Package.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=1,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.03 cusr  0.00 csys =  0.06 CPU)
Result: FAIL
```

A bit of poking reveals that `ALPM::strerror` does indeed not exist (although it is seemingly used in a number of places), but `ALPM::alpm_strerror` exists as a method. I changed the strerror usage in the test to maybe get a more useful error message:

```patch
diff --git a/t/03-Package.t b/t/03-Package.t
index 557a17c..31b5f4c 100644
--- a/t/03-Package.t
+++ b/t/03-Package.t
@@ -22,7 +22,7 @@ if($pkg){
        pass $msg;
 }else{
        fail $msg;
-       die $alpm->strerror;
+       die $alpm->alpm_strerror;
 }
 
 my @methnames = qw{ requiredby name version desc
```

And indeed, this gives a more descriptive error message:
```
invalid or corrupted package at t/03-Package.t line 25.
```

This is how far I got with my limited time budget and virtually non-existent experience with XS-based Perl modules.

**Comment by juster** [comment]
Thanks for the heads up. Those two issues are fixed.

The strerror problem was a simple mistake on my part. I likely forgot to remove the "alpm_" prefix when moving the function. The invalid or corrupted package message is caused when the test attempts to load the fake package for testing purposes. These packages are hand-crafted and the .PKGINFO file format changed very slightly in the new pacman.
